"""Regenerate Great Docs recipe pages from usage.py code builders."""

from __future__ import annotations

import ast
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parents[1]
USAGE_PATH = ROOT / "usage.py"
RECIPES_DIR = ROOT / "great-docs" / "recipes"
GENERATED_BANNER = (
    "<!-- Generated by scripts/generate_recipes.py. "
    "Edit usage.py to change the code examples. -->"
)

BUILDER_HELPERS = (
    "serialize_states_code_value",
    "resolve_states_demo_config",
    "format_table_property_value",
)


@dataclass(frozen=True)
class RecipeSpec:
    slug: str
    title: str
    description: str
    source: str
    builder_name: str
    builder_kwargs: dict[str, Any] | None = None
    builder_args: tuple[Any, ...] | None = None
    media: str | None = None
    sections: tuple[tuple[str, str, dict[str, Any] | None, tuple[Any, ...] | None], ...] | None = None


def extract_function_sources(names: set[str]) -> dict[str, str]:
    source = USAGE_PATH.read_text(encoding="utf-8")
    tree = ast.parse(source)
    extracted: dict[str, str] = {}

    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name in names:
            segment = ast.get_source_segment(source, node)
            if segment:
                extracted[node.name] = textwrap.dedent(segment)

    missing = names - set(extracted)
    if missing:
        raise RuntimeError(f"Missing builder functions in usage.py: {sorted(missing)}")

    return extracted


def exec_usage_preamble(namespace: dict[str, Any]) -> None:
    source = USAGE_PATH.read_text(encoding="utf-8")
    tree = ast.parse(source)
    preamble_nodes: list[ast.stmt] = []
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name.startswith("build_"):
            break
        preamble_nodes.append(node)

    module = ast.Module(body=preamble_nodes, type_ignores=[])
    exec(compile(module, str(USAGE_PATH), "exec"), namespace)


def build_usage_namespace(recipes: list[RecipeSpec]) -> dict[str, Any]:
    names = {spec.builder_name for spec in recipes}
    for recipe in recipes:
        if recipe.sections:
            names.update(section[1] for section in recipe.sections)
    names.update(BUILDER_HELPERS)

    namespace: dict[str, Any] = {"__builtins__": __builtins__}
    exec_usage_preamble(namespace)
    for name, source in extract_function_sources(names).items():
        exec(source, namespace, namespace)

    return namespace


def resolve_builder_kwargs(
    recipe: RecipeSpec, namespace: dict[str, Any]
) -> dict[str, Any] | None:
    if recipe.builder_kwargs is None:
        return None

    resolved = dict(recipe.builder_kwargs)
    if (
        recipe.builder_name == "build_table_properties_code"
        and resolved.get("config") is None
    ):
        resolved["config"] = namespace["TABLE_PROPERTIES_DEFAULTS"]
    if recipe.builder_name == "build_states_code":
        resolved = {**namespace["STATES_DEMO_DEFAULTS"], **resolved}
    return resolved


def call_builder(
    namespace: dict[str, Any],
    builder_name: str,
    *,
    builder_kwargs: dict[str, Any] | None = None,
    builder_args: tuple[Any, ...] | None = None,
) -> str:
    builder = namespace[builder_name]
    if builder_kwargs is not None:
        return builder(**builder_kwargs)
    if builder_args is not None:
        return builder(*builder_args)
    return builder()


def render_code_block(code: str) -> str:
    return "\n".join(["```python", code.rstrip(), "```", ""])


def render_recipe_page(recipe: RecipeSpec, namespace: dict[str, Any]) -> str:
    frontmatter = "\n".join(
        [
            "---",
            f"title: {recipe.title}",
            f"description: {recipe.description!r}",
            "bread-crumbs: false",
            "---",
            "",
        ]
    )
    body = [
        GENERATED_BANNER,
        "",
        f"# {recipe.title}",
        "",
        recipe.description,
        "",
        f"Source: `{recipe.source}`.",
        "",
    ]

    if recipe.media:
        body.extend(
            [
                f"![{recipe.title} preview](../assets/examples/{recipe.media})",
                "",
            ]
        )

    if recipe.sections:
        for heading, builder_name, kwargs, args in recipe.sections:
            code = call_builder(
                namespace,
                builder_name,
                builder_kwargs=kwargs,
                builder_args=args,
            )
            body.extend([f"## {heading}", "", render_code_block(code)])
    else:
        code = call_builder(
            namespace,
            recipe.builder_name,
            builder_kwargs=resolve_builder_kwargs(recipe, namespace),
            builder_args=recipe.builder_args,
        )
        body.append(render_code_block(code))

    return frontmatter + "\n".join(body)


def render_index(recipes: list[RecipeSpec]) -> str:
    frontmatter = "\n".join(
        [
            "---",
            "title: Recipes",
            "description: Copy-pasteable examples generated from usage.py.",
            "bread-crumbs: false",
            "---",
            "",
        ]
    )
    lines = [
        GENERATED_BANNER,
        "",
        "# Recipes",
        "",
        "These examples are generated from the code snippets that power the "
        "interactive `usage.py` demo, so the documentation and local demo stay "
        "anchored to the same source.",
        "",
    ]
    for recipe in recipes:
        lines.extend(
            [
                f"## [{recipe.title}]({recipe.slug}.qmd)",
                "",
                recipe.description,
                "",
            ]
        )
    return frontmatter + "\n".join(lines)


RECIPES: list[RecipeSpec] = [
    RecipeSpec(
        slug="basic-formatting",
        title="Basic Formatting",
        description=(
            "Render plain records with formatted currency, progress, badges, "
            "links, and Mantine table styling."
        ),
        source="usage.py::build_basic_formatting_code()",
        builder_name="build_basic_formatting_code",
        media="hero-basic-formatting.png",
    ),
    RecipeSpec(
        slug="client-side-selection",
        title="Client-side Selection",
        description=(
            "Enable checkbox selection and read selected row IDs from a normal "
            "Dash callback prop."
        ),
        source="usage.py::build_selection_code()",
        builder_name="build_selection_code",
        media="client-side-selection.png",
    ),
    RecipeSpec(
        slug="row-expansion",
        title="Row Expansion",
        description=(
            "Attach expandable detail panels and inspect the expansion state "
            "emitted by the table."
        ),
        source="usage.py::build_expanding_rows_code()",
        builder_name="build_expanding_rows_code",
        media="row-expansion.png",
    ),
    RecipeSpec(
        slug="nested-tables",
        title="Nested Tables",
        description=(
            "Use grouped rows and nested table structures for hierarchical datasets."
        ),
        source="usage.py::build_nested_tables_code()",
        builder_name="build_nested_tables_code",
    ),
    RecipeSpec(
        slug="async-nested-tables",
        title="Async Nested Tables",
        description=(
            "Hydrate child rows from callbacks while preserving the same nested "
            "table interaction model."
        ),
        source="usage.py::build_async_nested_tables_code()",
        builder_name="build_async_nested_tables_code",
    ),
    RecipeSpec(
        slug="server-pagination-sorting",
        title="Server Pagination and Sorting",
        description=(
            "Drive paging, sorting, and search from a callback that sends only "
            "the current slice of records."
        ),
        source="usage.py::build_server_pagination_code()",
        builder_name="build_server_pagination_code",
        media="server-pagination.png",
    ),
    RecipeSpec(
        slug="empty-loading-states",
        title="Empty and Loading States",
        description=(
            "Swap data, fetching flags, loader props, and empty-state content "
            "from one table configuration."
        ),
        source="usage.py::build_states_code(**STATES_DEMO_DEFAULTS)",
        builder_name="build_states_code",
        builder_kwargs=dict(
            state_mode="loading",
            loader_type="oval",
            loader_color="blue",
            loader_size="md",
            loader_blur=2,
            empty_text="No employees found",
            table_min_height=220,
        ),
    ),
    RecipeSpec(
        slug="fixed-height-scrolling",
        title="Fixed-height Scrolling",
        description=(
            "Constrain the table body to a fixed viewport while keeping the "
            "header and pagination stable."
        ),
        source="usage.py::build_scrolling_code(height=300)",
        builder_name="build_scrolling_code",
        builder_kwargs={"height": 300},
    ),
    RecipeSpec(
        slug="infinite-scrolling",
        title="Infinite Scrolling",
        description=(
            "Append rows from a callback when the user scrolls to the bottom "
            "edge of a fixed-height table."
        ),
        source="usage.py::build_infinite_scrolling_code()",
        builder_name="build_infinite_scrolling_code",
    ),
    RecipeSpec(
        slug="table-properties",
        title="Table Properties",
        description=(
            "Apply common Mantine table props through the chainable "
            "update_table_properties helper."
        ),
        source="usage.py::build_table_properties_code(TABLE_PROPERTIES_DEFAULTS)",
        builder_name="build_table_properties_code",
        builder_kwargs={"config": None},
    ),
    RecipeSpec(
        slug="column-properties",
        title="Column Properties",
        description=(
            "Configure headers, widths, footers, responsive visibility, ellipsis, "
            "and custom cell presentation."
        ),
        source="usage.py::build_column_properties_code()",
        builder_name="build_column_properties_code",
    ),
    RecipeSpec(
        slug="column-filtering",
        title="Column Filtering",
        description=(
            "Render Dash filter controls in column popovers and combine them "
            "with table filter state."
        ),
        source="usage.py::build_column_filtering_code()",
        builder_name="build_column_filtering_code",
        media="column-filtering.png",
    ),
    RecipeSpec(
        slug="column-dragging",
        title="Column Dragging",
        description=(
            "Persist draggable and toggleable column preferences with a browser "
            "storage key."
        ),
        source='usage.py::build_column_dragging_code("demo-column-dragging")',
        builder_name="build_column_dragging_code",
        builder_kwargs={"store_key": "demo-column-dragging"},
    ),
    RecipeSpec(
        slug="column-resizing",
        title="Column Resizing",
        description=(
            "Enable user-resizable columns and preserve widths through the same "
            "column storage model."
        ),
        source="usage.py::build_column_resizing_code()",
        builder_name="build_column_resizing_code",
    ),
    RecipeSpec(
        slug="column-grouping",
        title="Column Grouping",
        description=(
            "Group related columns under flat or nested headers with ColumnGroup "
            "and group_columns."
        ),
        source="usage.py::build_group_columns_code()",
        builder_name="build_group_columns_code",
    ),
    RecipeSpec(
        slug="row-properties",
        title="Row Properties",
        description=(
            "Style rows with Dash-safe selector rules for colors, classes, "
            "inline styles, and attributes."
        ),
        source="usage.py::build_row_properties_code()",
        builder_name="build_row_properties_code",
    ),
    RecipeSpec(
        slug="row-dragging",
        title="Row Dragging",
        description=(
            "Enable Dash-native row reordering and inspect the emitted drag payload."
        ),
        source="usage.py::build_row_dragging_code()",
        builder_name="build_row_dragging_code",
        media="row-dragging.png",
    ),
    RecipeSpec(
        slug="row-ids",
        title="Row IDs",
        description=(
            "Use non-standard or composite record identifiers for selection, "
            "expansion, and drag state."
        ),
        source="usage.py::build_row_ids_code()",
        builder_name="build_row_ids_code",
    ),
    RecipeSpec(
        slug="row-and-cell-clicks",
        title="Row and Cell Clicks",
        description=(
            "Apply interactive affordances and handle rowClick and cellClick "
            "payloads in callbacks."
        ),
        source=(
            "usage.py::build_row_click_code(), usage.py::build_cell_click_code()"
        ),
        builder_name="build_row_click_code",
        sections=(
            ("Row Click", "build_row_click_code", None, None),
            ("Cell Click", "build_cell_click_code", None, None),
        ),
    ),
    RecipeSpec(
        slug="inline-editing",
        title="Inline Editing",
        description=(
            "Define DMC editor components directly on editable columns and "
            "preview edited records."
        ),
        source="usage.py::build_inline_edit_code()",
        builder_name="build_inline_edit_code",
    ),
    RecipeSpec(
        slug="rtl-support",
        title="RTL Support",
        description=(
            "Switch a table into right-to-left layout while keeping pinning, "
            "alignment, and pagination coherent."
        ),
        source='usage.py::build_rtl_support_code(direction="rtl", height=260)',
        builder_name="build_rtl_support_code",
        builder_kwargs={"direction": "rtl", "height": 260},
    ),
    RecipeSpec(
        slug="advanced-controls",
        title="Advanced Controls",
        description=(
            "Compose selection, pagination, sorting, search, and layout helpers "
            "into one fluent table setup."
        ),
        source="usage.py::build_advanced_controls_code()",
        builder_name="build_advanced_controls_code",
    ),
    RecipeSpec(
        slug="stock-portfolio",
        title="Stock Portfolio",
        description=(
            "Build a wider market-data table with grouped headers, editable "
            "tickers, sparklines, and currency columns."
        ),
        source="usage.py::build_stock_portfolio_code()",
        builder_name="build_stock_portfolio_code",
    ),
    RecipeSpec(
        slug="custom-components",
        title="Custom Components",
        description="Use Dash components for custom loaders and no-records states.",
        source="usage.py::build_custom_components_code()",
        builder_name="build_custom_components_code",
    ),
]


def main() -> None:
    namespace = build_usage_namespace(RECIPES)
    RECIPES_DIR.mkdir(parents=True, exist_ok=True)

    for recipe in RECIPES:
        output_path = RECIPES_DIR / f"{recipe.slug}.qmd"
        output_path.write_text(render_recipe_page(recipe, namespace), encoding="utf-8")

    (RECIPES_DIR / "index.qmd").write_text(render_index(RECIPES), encoding="utf-8")
    print(f"Generated {len(RECIPES)} recipes in {RECIPES_DIR}")


if __name__ == "__main__":
    main()
