.dashMantineDatatable_js_metadata <- function() {
deps_metadata <- list(`dash_mantine_datatable` = structure(list(name = "dash_mantine_datatable",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashMantineDatatable.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashMantineDatatable",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_mantine_datatable` = structure(list(name = "dash_mantine_datatable",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashMantineDatatable.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashMantineDatatable",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_mantine_datatable` = structure(list(name = "dash_mantine_datatable",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_mantine_datatable.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashMantineDatatable",
all_files = FALSE), class = "html_dependency"),
`dash_mantine_datatable` = structure(list(name = "dash_mantine_datatable",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_mantine_datatable.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashMantineDatatable",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
